### ISSUE TITLE
General: Content Service Errors

### ISSUE THREAD

**Issue by mikaelajoyce** [engagementlab/engagement-lab-website-2.x#142]
Content service error message on "About" page, does not disappear until page is refreshed/cache is cleared. Appears on other pages when navigated away from. ![Content Service Error.png](https://images.zenhubusercontent.com/5f7e099c94d0e721aca273ea/dee64841-3a4c-487d-957d-869fb8e97fae)

**Comment by johnnycrich** [comment]
@mikaelajoyce Does clicking "dismiss" not hide it?

**Comment by johnnycrich** [comment]
Looks like this is behaving as designed. Closing.
