### ISSUE TITLE
Add ability to change copy text color

### ISSUE THREAD

**Issue by mikaelajoyce** [engagementlab/engagement-lab-website-2.x#155]
Add ability to change the color of text, so hyperlinks appear different than the regular body text.

https://qa.elab.emerson.edu/graduate/apply 

(for the application instructions, which link externally to the Emerson website)

**Comment by johnnycrich** [comment]
@mikaelajoyce I will need some time to figure out how to make color editable overall in CMS, but I can do this manually for now.
